fst_Career_Portal_Dev/Controllers/ForgotPasswordController.cs
using fst_Career_Portal_Dev.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Reflection;

namespace fst_Career_Portal_Dev.Controllers
{
    public class ForgotPasswordController : Controller
    {
        // GET: ForgotPassword
        public ActionResult Index(ForgotPasswordMdl model)
        {
            string buttonValue = Request.Form["ForgotPasswrd"];

            if (buttonValue == "ForgotPass")
            {
                try
                {
                    //string userName = WhoLogged_user;
                    // string username = model.username;
                    // string email = model.emailaddress;
                    // string Password = model.NewPasswordChange;
                    // string ConfirmPassword = model.NewConfirmPasswordChange;
                    // int res = 0;

                    // var connection = ConfigurationManager.ConnectionStrings["db_connection"].ToString();
                    // SqlConnection sql_conn = new SqlConnection(connection);

                    // SqlCommand sql_cmd = new SqlCommand("cpMst_ForgotUserPassword_Main", sql_conn);
                    // sql_cmd.CommandType = CommandType.StoredProcedure;

                    // sql_cmd.Parameters.AddWithValue("@cp_usrNm", username);
                    // sql_cmd.Parameters.AddWithValue("@cpUsrEmail", email);
                    // sql_cmd.Parameters.AddWithValue("@cpUsrNewPsswrd", Password);
                    // sql_cmd.Parameters.AddWithValue("@cpUsrNewCPsswrd", ConfirmPassword);
                    // SqlParameter sql_param = new SqlParameter("@IsVld", SqlDbType.Int);
                    // sql_param.ParameterName = "@IsVld";
                    // sql_param.Direction = ParameterDirection.Output;
                    // sql_cmd.Parameters.Add(sql_param);

                    //res = (int)sql_param.Value;
                    string username = model.username;
                    string email = model.emailaddress;
                    string Password = model.NewPasswordChange;
                    string ConfirmPassword = model.NewConfirmPasswordChange;

                    var connection = ConfigurationManager.ConnectionStrings["db_connection"].ToString();
                    SqlConnection sql_conn = new SqlConnection(connection);

                    SqlCommand sql_cmd = new SqlCommand("cpMst_ForgotUserPassword_Main1", sql_conn);
                    sql_cmd.CommandType = CommandType.StoredProcedure;

                    sql_cmd.Parameters.AddWithValue("@cp_usrNm", username);
                    sql_cmd.Parameters.AddWithValue("@cpUsrEmail", email);
                    sql_cmd.Parameters.AddWithValue("@cpUsrNewPsswrd", Password);
                    sql_cmd.Parameters.AddWithValue("@cpUsrNewCPsswrd", ConfirmPassword);

                    // Define the output parameter and add it to the command
                    SqlParameter sql_param = new SqlParameter("@IsVld", SqlDbType.Int);
                    sql_param.Direction = ParameterDirection.Output;
                    sql_cmd.Parameters.Add(sql_param);

                    sql_conn.Open();
                    sql_cmd.ExecuteNonQuery();

                    // Now you can safely retrieve the output parameter value
                    int res = (int)sql_param.Value;

                    if (res == 4)
                    {
                        TempData["PasswordChangeSuccess"] = "Password Changed...was successful";
                    }
                    if (res == 3)
                    {
                        TempData["PasswordChangeError3"] = " Error...Password and confirm password dont match";
                    }
                    if (res == 2)
                    {
                        TempData["PasswordChangeError2"] = " Error...Email Address Doesnt Exist";
                    }
                    if (res == 1)
                    {
                        TempData["PasswordChangeError1"] = " Error..Username doesnt correct";
                    }

                    return RedirectToAction("Index");
                }
                catch (Exception )
                {
                    TempData["PasswordChangeError"] = "Password Changed error..please try again";
                    return RedirectToAction("Index");
                }
            }

            return View("Index");
        }

        public ActionResult ChangePassword(ForgotPasswordMdl model)
        {
            try
            {
                //string userName = WhoLogged_user;
                string username = model.username;
                string email = model.emailaddress;
                string Password = model.NewPasswordChange;
                string ConfirmPassword = model.NewConfirmPasswordChange;

                var connection = ConfigurationManager.ConnectionStrings["db_connection"].ToString();
                SqlConnection sql_conn = new SqlConnection(connection);

                SqlCommand sql_cmd = new SqlCommand("cpMst_ForgotUserPassword_Main", sql_conn);
                sql_cmd.CommandType = CommandType.StoredProcedure;

                sql_cmd.Parameters.AddWithValue("@cp_usrNm", username);
                sql_cmd.Parameters.AddWithValue("@cpUsrEmail", email);
                sql_cmd.Parameters.AddWithValue("@cpUsrNewPsswrd", Password);
                sql_cmd.Parameters.AddWithValue("@cpUsrNewCPsswrd", ConfirmPassword);
                SqlParameter sql_param = new SqlParameter();
                sql_param.ParameterName = "@IsVld";
                sql_param.SqlDbType = SqlDbType.Int;
                sql_param.Direction = ParameterDirection.Output;
                sql_cmd.Parameters.Add(sql_param);

                int res = (int)sql_param.Value;
                sql_conn.Open();
                sql_cmd.ExecuteNonQuery();

                if (res == 4)
                {
                    TempData["PasswordChangeSuccess"] = "Password Changed...was successful";
                }
                if (res == 3)
                {
                    TempData["PasswordChangeError3"] = " Error...Password and confirm password dont match";
                }
                if (res == 2)
                {
                    TempData["PasswordChangeError2"] = " Error...Email Address Doesnt Exist";
                }
                if (res == 1)
                {
                    TempData["PasswordChangeError1"] = " Error..Username doesnt correct";
                }



                return RedirectToAction("Index");
            }
            catch (Exception )
            {
                TempData["PasswordChangeError"] = "Password Changed error..please try again";
                return RedirectToAction("Index");
            }
        }
    }
}

fst_Career_Portal_Dev/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using fst_Career_Portal_Dev.Models;

namespace fst_Career_Portal_Dev.Controllers
{
    public class LoginController : Controller
    {
        Data_Access_Layer.dba dbaLayer = new Data_Access_Layer.dba();
        // GET: Login
        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult DropDownControl()
        {
            LoginMdl lrf = new LoginMdl();
            {

                lrf.login_roleList = GetUserRoleList();

            };

            return View(lrf);

        }

        public List<UserRole_list_login> GetUserRoleList()

        {

            var connection = ConfigurationManager.ConnectionStrings["db_connection"].ToString();

            SqlConnection sql_conn = new SqlConnection(connection);

            SqlCommand sql_cmd = new SqlCommand("Select * as Name From Customers", sql_conn);

            sql_conn.Open();

            SqlDataReader idr = sql_cmd.ExecuteReader();

            List<UserRole_list_login> user_roles_ = new List<UserRole_list_login>();

            if (idr.HasRows)

            {

                while (idr.Read())

                {

                    user_roles_.Add(new UserRole_list_login

                    {

                        Login_RoleID = Convert.ToInt32(idr["customerId"]),

                        Login_RoleName = Convert.ToString(idr["Name"]),

                    });

                }

            }



            sql_conn.Close();

            return user_roles_;

        }

        [HttpPost]
        public ActionResult Index(FormCollection fc,LoginMdl model)
        {
            var btnResult = fc["button"];

            if (btnResult == "Register")
            {
                return RedirectToAction("Index", "Register");
            }
            else if (btnResult == "Login")
            {
                if (string.IsNullOrEmpty(model.Username))
                {
                    TempData["LoginUsernameError"] = "Username is required.";

                    return View("Index"); // Return back to the view
                }
                if (string.IsNullOrEmpty(model.Password))
                {
                    TempData["LoginPasswordError"] = "Password is required.";

                    return View("Index"); // Return back to the view
                }
                int res = dbaLayer.User_Login(fc["username"], fc["password"]);
                LoginMdl lrf = new LoginMdl();
                if (res == 1)
                {
                    TempData["LoginSuccess"] = "Login is successfully!";
                    return RedirectToAction("Index","Dashboard");
                }
            }
            
            TempData["LoginError"] = "Username/Password doesnt exist or is wrong....";
            return View();
        }

        public ActionResult Dashboard()
        {
            return View();
        }

    }
}

fst_Career_Portal_Dev/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Xml.Linq;
using fst_Career_Portal_Dev.Models;
using static fst_Career_Portal_Dev.Models.RegisterMdl;

namespace fst_Career_Portal_Dev.Controllers
{

    public class RegisterController : Controller
    {
        //Data Access
        Data_Access_Layer.dba dbaLayer = new Data_Access_Layer.dba();
        // GET: Register

        [HttpGet]
        public ActionResult Index()
        {
            RegisterMdl user_role_ = new RegisterMdl();
            user_role_.UserRoleList = GetDropdownOptionsFromDatabase();

            return View(user_role_);
        }

        private List<RegisterMdl> GetDropdownOptionsFromDatabase()
        {

            var connection = ConfigurationManager.ConnectionStrings["db_connection"].ToString();

            SqlConnection con = new SqlConnection(connection);

            SqlCommand cmd = new SqlCommand("SELECT cp_usrRlId, cp_usrRlNm FROM [Career_Portal_Dev_1].[dbo].[mst_cpUserRole_tbl]", con);

            con.Open();

            SqlDataReader idr = cmd.ExecuteReader();

            List<RegisterMdl> user_roles = new List<RegisterMdl>();

            if (idr.HasRows)

            {
                while (idr.Read())
                {
                    user_roles.Add(new RegisterMdl

                    {
                        Register_RoleID = Convert.ToInt32(idr["cp_usrRlId"]),

                        Register_RoleName = Convert.ToString(idr["cp_usrRlNm"]),
                    });
                }
            }
            con.Close();

            return user_roles;
        }


        [HttpPost]
        public ActionResult Index(FormCollection fc,RegisterMdl model)
        {

            if (string.IsNullOrEmpty(model.Username))
            {
                TempData["RegisterUsernameError"] = "Username is required.";
                // Other validation logic 9169315254
                return View("Index"); // Return back to the view
            }
            if (string.IsNullOrEmpty(model.Password))
            {
                TempData["RegisterPasswordError"] = "Password is required.";
                // Other validation logic
                return View(model); // Return back to the view
            }
            if (string.IsNullOrEmpty(model.ConfirmPassword))
            {
                TempData["RegisterPasswordConfirmError"] = "Confirm Password is required.";
                // Other validation logic
                return View(model); // Return back to the view
            }
            if (string.IsNullOrEmpty(model.Email))
            {
                TempData["RegisterEmailError"] = "Email is required.";
                // Other validation logic
                return View(model); // Return back to the view
            }
            if (string.IsNullOrEmpty(model.FirstName))
            {
                TempData["RegisterFirstNameError"] = "First Name is required.";
                // Other validation logic
                return View(model); // Return back to the view
            }
            if (string.IsNullOrEmpty(model.LastName))
            {
                TempData["RegsiterLastNameError"] = "Last Name is required.";
                // Other validation logic
                return View(model); // Return back to the view
            }
            if (string.IsNullOrEmpty(model.NationalID))
            {
                TempData["RegisterNationalIDError"] = "National ID is required.";
                // Other validation logic
                return View(model); // Return back to the view
            }
            if (string.IsNullOrEmpty(model.SelectedGrade))
            {
                TempData["RegisterGradeError"] = "Grade is required.";
                // Other validation logic
                return View(model); // Return back to the view
            }
            if (string.IsNullOrEmpty(model.School))
            {
                TempData["RegisterSchoolError"] = "School is required.";
                // Other validation logic
                return View(model); // Return back to the view
            }
            if (string.IsNullOrEmpty(model.SelectedGender))
            {
                TempData["RegisterGenderError"] = "Gender is required.";
                // Other validation logic
                return View(model); // Return back to the view
            }
            int selectedRoleId = model.SelectedRoleId;

            string selectedG = model.SelectedGender;

            string selectedGrade = model.SelectedGrade;

            int res = dbaLayer.User_Registration(fc["username"], fc["password"], selectedRoleId, fc["FirstName"], fc["LastName"],
                                                  fc["Email"], selectedGrade, selectedG, fc["School"], fc["Province"], fc["NationalID"]);
            LoginMdl lrf = new LoginMdl();
            RegisterMdl user_role_ = new RegisterMdl();
            //user_role_.UserRoleList = GetDropdownOptionsFromDatabase();
            if (res == 88)
            {
                TempData["ToastMessageSuccess"] = "Successful...Your registration has been successful.";
                user_role_.UserRoleList = GetDropdownOptionsFromDatabase();
                ViewBag.Message = string.Format("Hello {0}.\\nCurrent Date and Time: {1}", fc["FirstName"], DateTime.Now.ToString());
                return RedirectToAction("Index", "Login");
            }
            else if (res == 2)
            {
                TempData["ToastMessage"] = "Error...User input email exists already.";
            }
            else if (res == 3)
            {
                TempData["ToastMessage"] = "Error...User input ID already exists.";
            }
            else if (res == 4 ) 
            {
                TempData["ToastMessage"] = "Error...Registration has gone wrong,notify the adminstrator.";
            }
            else if (res == 5)
            {
                TempData["ToastMessage"] = "Error...Registration has gone wrong,notify the adminstrator.";
            }
            else if (res == 6)
            {
                TempData["ToastMessage"] = "Error..ID citizenship is not zero (non-South Africa)";
            }
            else if (res == 7)
            {
                TempData["ToastMessage"] = "Error...Something has gone wrong...notify the adminstrator.";
            }
            else if (res == 8)
            {
                TempData["ToastMessage"] = "Error...Input ID is wrong.";
            }
            return View(user_role_);
        }
    }
}

fst_Career_Portal_Dev/Views/Login/Index.cshtml
@model fst_Career_Portal_Dev.Models.LoginMdl

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LoginLayoutPage.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <h1 class="header-w3ls">
        FASSET CAREER PORTAL<span class="trademark_1" style=" vertical-align: super;">&#174;</span>
    </h1>
    <div class="art-bothside">
        <div class="mid-cls">
            <div class="art-right-w3ls">
                <h1 class="header-w3ls">Portal login</h1>
                <p>Facilitating the achievement of world-class finance and accounting services skills. </p>
                <form action="#" method="post">
                    <div class="main">
                        <div class="form-left-to-w3l">
                            @*<input type="text" name="username" placeholder="Username" required="">*@
                            @Html.TextBoxFor(e => e.Username, new { @class = "form-control", placeholder = "Username *", name = "username" })
                            @if (TempData["LoginUsernameError"] != null)
                            {
                                <script>
                                    $(document).ready(function () {
                                            var submitButton = '@ViewBag.SubmitButton'; // Use your actual ViewBag variable here
                                        if (submitButton !== 'Register') {
                                            toastr.error('@TempData["LoginUsernameError"]');
                                        }else {
                                            // Redirect to registration page
                                            window.location.href = '@Url.Action("Index", "Register")'; // Modify the action and controller names as needed
                                        }

                                        });
                                </script>
                            }
                        </div>
                        <div class="main">
                            <div class="form-left-to-w3l">
                                @*<input type="password" name="password" placeholder="Password" id="password" required="">*@
                                @Html.PasswordFor(e => e.Password, new { @class = "form-control", placeholder = "Password *", name = "password" })
                                @if (TempData["LoginPasswordError"] != null)
                                {
                                    <script>
                                        $(document).ready(function () {
                                        var submitButton = '@ViewBag.SubmitButton'; // Use your actual ViewBag variable here
                                            if (submitButton !== 'Register') {
                                                toastr.error('@TempData["LoginPasswordError"]');
                                            }
                                        });
                                    </script>
                                }
                                <div class="clear"></div>
                            </div>
                        </div>
                        <!--<div class="form-right-w3ls">-->
                        @*<select id="company" class="form-control">
                                <option value="" selected disabled>Select Role Type</option>
                                <option>Student</option>
                                <option>Fasset Admin</option>
                                <option>Service Provider</option>
                            </select>*@
                        <!--@*Html.DropDownList("role", ViewBag.Roles as SelectList, "Select Category")*@-->
                        @*@Html.DropDownListFor(m => m., new SelectList(Enum.GetValues(typeof(UserRoles))), "Select Role")*@
                        <!--</div>-->

                    </div>

                    <!--<div class="btnn">
                    <button type="submit" name="button" value="Login">Sign In</button>-->
                    @*<button id="cust_button" type="button" onclick="location.href='../Register/Index'">Sign Up</button>*@

                    <!--<button name="button" value="Register" type="submit" onclick="location.href='@Url.Action("Index", "Register")'">Sign Up</button>-->
                    @*onclick="location.href='<%: Url.Action("Action", "Controller") %>'"*@
                    <!--</div>-->
                    <div class="btnn">
                        <button type="submit" name="button" value="Login" style="background-color: #00008B; color: white; ">Sign In</button>

                        <button name="button" value="Register" type="submit" style="background-color: #00008B; color: white; " onclick="location.href='@Url.Action("Index", "Register")'">Sign Up</button>
                    </div>
                </form>
                <div class="banner-agileits-btm">
                    <div class="w3layouts_more-buttn">
                        <h3 class="forgotPass">Did you forget your password..? <a href="#small-dialog1 " class="play-icon popup-with-zoom-anim" onclick="location.href='@Url.Action("Index", "ForgotPassword")'">Reset Password</a></h3>
                    </div>
                </div>
            </div>
            <div class="art-left-w3ls">
                <img src="~/Content/images/fasset_logo_1-removebg-preview (1).png" />
            </div>
        </div>
    </div>
    <div class="copy">
        <p>&copy;2022 FASSET Career Portal. All Rights Reserved | Design by <a href="http:fasset.org.za" target="_blank">FASSET</a></p>
    </div>
    @*if (TempData["LoginSuccessful"] != null)
        {
            <script>
            $(document).ready(function () {
                toastr.success('@TempData["Login successful"]');
            });
            </script>
        }
        if (TempData["ErrorMessage"] != null)
        {
            <script>
            $(document).ready(function () {
                toastr.error('@TempData["ErrorMessage"]');
            });
            </script>*@
}
<!--js working-->
@*<script src="~/Assets/js/jquery-2.2.3.min.js"></script>*@
<!--//js working-->
@*<script>
        var password = document.getElementById("password")
            , confirm_password = document.getElementById("confirm_password");

        function validatePassword() {
            if (password.value != confirm_password.value) {
                confirm_password.setCustomValidity("Passwords Don't Match");
            } else {
                confirm_password.setCustomValidity('');
            }
        }

        password.onchange = validatePassword;
        confirm_password.onkeyup = validatePassword;
    </script>*@
<!--//scripts-->
@*<script src="~/Assets/js/jquery.magnific-popup.js"></script>*@
<!-- //pop-up-box -->
<script>
    $(document).ready(function () {
        $('.popup-with-zoom-anim').magnificPopup({
            type: 'inline',
            fixedContentPos: false,
            fixedBgPos: true,
            overflowY: 'auto',
            closeBtnInside: true,
            preloader: false,
            midClick: true,
            removalDelay: 300,
            mainClass: 'my-mfp-zoom-in'
        });

    });
</script>

<!-- //pop-up-box -->